name: CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
    types: [ 'opened', 'reopened', 'edited', 'synchronize' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cancel_previous:

    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          workflow_id: ${{ github.event.workflow.id }}

  ga4-test:
    needs: cancel_previous
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout source branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: cache gradle dependencies
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-core-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-core-

      - name: Run Tests
        run: ./gradlew ga4:test

      - name: Generate coverage report
        run: ./gradlew ga4:codeCoverageReport

